### ISSUE TITLE
Interface error

### ISSUE THREAD

**Issue by cufano** [Nembie/iban-rule#2] opened 2024-03-05 07:32 UTC
Hello, I get this error when use the validation rule as indicated:
Use Laravel 9 and PHP 8.1

> Interface "Illuminate\Contracts\Validation\ValidationRule" not found

```
use Nembie\IbanRule\ValidIban;
'account_iban' => ['required', new ValidIban()],
```

What am I missing?

**Comment by Nembie** [comment] 2024-03-05 08:21
Hi @cufano!
Thanks for reporting, the problem is because the package doesn't support version 9 of Laravel but 10 and above for now. ASAP I will try to find a way to make it compatible with old versions of Laravel if there are no incompatibilities and I will add the required version in the doc.

For now I'm sorry but I have to close the issue, if I can help you in any other way I remain available! 😄

**Closed by Nembie** 2024-03-05 08:21 UTC

**Comment by adriallongarriu** [comment] 2024-08-26 13:47
I was facing the same error in laravel 9.
I create a new rule `php artisan make:rule ValidIban` and add the code of the validation the import is diferent use `Illuminate\Contracts\Validation\Rule` and you need to ajust "passes" and "message" functions.

```php
use Illuminate\Contracts\Validation\Rule;

class ValidIban implements Rule
{
    public function passes($attribute, $value)
    {
        return $this->checkIBAN($value);
    }

    public function message()
    {
        return trans('validation.iban');
    }

   // code from validation checkIBAN function and getCountryRules
   ...
}
```
